### ISSUE TITLE
[BUG] Using from_qiskit is broken in v0.34

### ISSUE THREAD

**Issue by trbromley** [PennyLaneAI/pennylane#5056]
### Expected behavior

The example in [`from_qiskit`](https://docs.pennylane.ai/en/stable/code/api/pennylane.from_qiskit.html) works.

### Actual behavior

The example in [`from_qiskit`](https://docs.pennylane.ai/en/stable/code/api/pennylane.from_qiskit.html) raises an exception.

### Additional information

Things work in v0.33.1

### Source code

```shell
import pennylane as qml
import qiskit

qc = qiskit.QuantumCircuit(2)
qc.rz(0.543, [0])
qc.cx(0, 1)
my_circuit = qml.from_qiskit(qc)

@qml.qnode(qml.device("default.qubit"))
def circuit(x):
    qml.RX(x, wires=1)
    my_circuit(wires=(1, 0))
    return qml.expval(qml.PauliZ(0))

circuit(0.5)
```

### Tracebacks

```shell
AttributeError: module 'pennylane.ops.qubit' has no attribute 'ops'
```

### System information

```shell
v0.34.0
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by trbromley** [comment]
My mistake - this was due to an incorrect version of `pennylane-qiskit` :+1:
