### ISSUE TITLE
[BUG] AttributeError: 'QNode' object has no attribute 'weights' (TorchLayer)

### ISSUE THREAD

**Issue by ankit27kh** [PennyLaneAI/pennylane#4584]
### Expected behavior

In previous versions, one could see the weights and the grads of the qnode TorchLayer by using:
```qlayer.weights``` and ```qlayer.weights.grad```
This no longer works in newer versions.

### Actual behavior

Trying to get the weights and grads gives an error

### Additional information

works in 0.30.0
does not work in later versions

I am not sure if this is a feature or a bug.
If it's not a bug, what's the new way to get to the weights and the grads?

### Source code

```shell
## This is the example from the documentation
import numpy as np
import pennylane as qml
import torch
import sklearn.datasets

n_qubits = 2
dev = qml.device("default.qubit", wires=n_qubits,shots=None)

@qml.qnode(dev,interface='torch',diff_method='backprop')
def qnode(inputs, weights):
    qml.templates.AngleEmbedding(inputs, wires=range(n_qubits))
    qml.templates.StronglyEntanglingLayers(weights, wires=range(n_qubits))
    return qml.expval(qml.PauliZ(0)), qml.expval(qml.PauliZ(1))

weight_shapes = {"weights": (3, n_qubits, 3)}

qlayer = qml.qnn.TorchLayer(qnode, weight_shapes)
clayer1 = torch.nn.Linear(2, 2)
clayer2 = torch.nn.Linear(2, 2)
softmax = torch.nn.Softmax(dim=1)
model = torch.nn.Sequential(clayer1, qlayer, clayer2, softmax)

samples = 10
x, y = sklearn.datasets.make_moons(samples)
y_hot = np.zeros((samples, 2))
y_hot[np.arange(samples), y] = 1

X = torch.tensor(x).float()
Y = torch.tensor(y_hot).float()

opt = torch.optim.SGD(model.parameters(), lr=0.5)
loss = torch.nn.L1Loss()

epochs = 2
batch_size = 5
batches = samples // batch_size

data_loader = torch.utils.data.DataLoader(list(zip(X, Y)), batch_size=batch_size,
                                          shuffle=True, drop_last=True)

for epoch in range(epochs):

    running_loss = 0

    for x, y in data_loader:
        opt.zero_grad()

        loss_evaluated = loss(model(x), y)
        loss_evaluated.backward()
        opt.step()
        print(model[1].weights) <-- These lines don't work in new versions
        print(model[1].weights.grad) <-- These lines don't work in new versions
        running_loss += loss_evaluated

    avg_loss = running_loss / batches
    print("Average loss over epoch {}: {:.4f}".format(epoch + 1, avg_loss))
```

### Tracebacks

```shell
print(model[1].weights)
  File "/site-packages/pennylane/qnn/torch.py", line 460, in __getattr__
    return getattr(self.qnode, item)
AttributeError: 'QNode' object has no attribute 'weights'
```

### System information

```shell
na
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by KetpuntoG** [comment]
Hi @ankit27kh ! :) 
You can access the quantum layer weights as follows:

`print(qlayer.qnode_weights) `

Regarding the `weights.grad`, I don't know exactly what do you want to get there. 
Could you give more details?

**Comment by ankit27kh** [comment]
Hey @KetpuntoG, `weights.grad` is supposed to give the calculated gradients for all these weights.

**Comment by ankit27kh** [comment]
Either way, if this is a layer to be used with torch, why not follow the torch convention? I would have hoped it'd behave like any other torch layer.

**Comment by KetpuntoG** [comment]
Thanks for the feedback, I will see if I can find the reason for this change
Anyway here is a solution :)

```python

weights = qlayer.qnode_weights["weights"]
print(weights)
print(weights.grad)

```

I hope this helps!

**Comment by albi3ro** [comment]
@ankit27kh Thanks for opening this bug report.  I have a fix up in #4611 that should solve your problem.

**Comment by albi3ro** [comment]
This issue should now be solved by #4611
