### ISSUE TITLE
[BUG] Single-precision raises error with the JAX JIT interface

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#3309]
### Expected behavior

Users can have single-precision workflows.

### Actual behavior

Error is raised because internally somewhere results with double precision are created.

### Source code

```shell
import jax
import pennylane as qml
from pennylane import numpy as np

dev = qml.device("default.qubit", wires=2)

@jax.jit
@qml.qnode(dev, interface="jax", diff_method="parameter-shift")
def circuit(a):
    qml.RX(a, wires=0)
    return qml.expval(qml.PauliZ(wires=0))

x = jax.numpy.array(0.1)
jax.jacobian(circuit)(x)
```

### Tracebacks

```shell
XlaRuntimeError: INTERNAL: Generated function failed: CpuCallback error: RuntimeError: Incorrect output dtype for return value 0: Expected: float32, Actual: float64
```

### System information

```shell
PL master
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by josh146** [comment]
Nice catch @antalszava! Is this a new bug compared to v0.26?

**Comment by eddddddy** [comment]
On Windows the error message is a lot more cryptic:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python38\lib\site-packages\jax\_src\traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "C:\Python38\lib\site-packages\jax\_src\api.py", line 1583, in vmap_f
    out_flat = batching.batch(
  File "C:\Python38\lib\site-packages\jax\linear_util.py", line 168, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "C:\Python38\lib\site-packages\jax\_src\tree_util.py", line 297, in __call__
    return self.fun(*args, **kw)
  File "C:\Python38\lib\site-packages\jax\_src\api.py", line 2423, in _vjp_pullback_wrapper
    ans = fun(*args)
  File "C:\Python38\lib\site-packages\jax\_src\tree_util.py", line 297, in __call__
    return self.fun(*args, **kw)
  File "C:\Python38\lib\site-packages\jax\interpreters\ad.py", line 140, in unbound_vjp
    arg_cts = backward_pass(jaxpr, reduce_axes, True, consts, dummy_args, cts)
  File "C:\Python38\lib\site-packages\jax\interpreters\ad.py", line 240, in backward_pass
    cts_out = get_primitive_transpose(eqn.primitive)(
  File "C:\Python38\lib\site-packages\jax\interpreters\ad.py", line 625, in call_transpose
    out_flat = primitive.bind(fun, *all_args, **params)
  File "C:\Python38\lib\site-packages\jax\core.py", line 1963, in bind
    return call_bind(self, fun, *args, **params)
  File "C:\Python38\lib\site-packages\jax\core.py", line 1979, in call_bind
    outs = top_trace.process_call(primitive, fun_, tracers, params)
  File "C:\Python38\lib\site-packages\jax\interpreters\batching.py", line 239, in process_call
    vals_out = call_primitive.bind(f_, *vals, **params)
  File "C:\Python38\lib\site-packages\jax\core.py", line 1963, in bind
    return call_bind(self, fun, *args, **params)
  File "C:\Python38\lib\site-packages\jax\core.py", line 1979, in call_bind
    outs = top_trace.process_call(primitive, fun_, tracers, params)
  File "C:\Python38\lib\site-packages\jax\core.py", line 689, in process_call
    return primitive.impl(f, *tracers, **params)
  File "C:\Python38\lib\site-packages\jax\_src\dispatch.py", line 233, in _xla_call_impl
    compiled_fun = xla_callable(fun, device, backend, name, donated_invars,
  File "C:\Python38\lib\site-packages\jax\linear_util.py", line 295, in memoized_fun
    ans = call(fun, *args)
  File "C:\Python38\lib\site-packages\jax\_src\dispatch.py", line 324, in _xla_callable_uncached
    return lower_xla_callable(fun, device, backend, name, donated_invars, False,
  File "C:\Python38\lib\site-packages\jax\_src\dispatch.py", line 934, in compile
    self._executable = XlaCompiledComputation.from_xla_computation(
  File "C:\Python38\lib\site-packages\jax\_src\dispatch.py", line 1052, in from_xla_computation
    compiled = compile_or_get_cached(backend, xla_computation, options,
  File "C:\Python38\lib\site-packages\jax\_src\dispatch.py", line 1006, in compile_or_get_cached
    return backend_compile(backend, computation, compile_options, host_callbacks)
  File "C:\Python38\lib\site-packages\jax\_src\profiler.py", line 313, in wrapper
    return func(*args, **kwargs)
  File "C:\Python38\lib\site-packages\jax\_src\dispatch.py", line 950, in backend_compile
    return backend.compile(built_c, compile_options=options)
jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: UNKNOWN: C:\Users\Edward\Documents\pennylane\pennylane\interfaces\jax_jit.py:253:1: error: 'mhlo.broadcast_in_dim' op requires the same element type for all operands and results
    return wrapped_exec(params)
^
C:\Users\Edward\Documents\pennylane\pennylane\interfaces\jax_jit.py:253:1: note: see current operation: %1 = "mhlo.broadcast_in_dim"(%0) {broadcast_dimensions = dense<> : tensor<0xi64>} : (tensor<f32>) -> tensor<2x2xf64>

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python38\lib\site-packages\jax\_src\api.py", line 1279, in jacfun
    jac = vmap(pullback)(_std_basis(y))
jaxlib.xla_extension.XlaRuntimeError: UNKNOWN: C:\Users\Edward\Documents\pennylane\pennylane\interfaces\jax_jit.py:253:1: error: 'mhlo.broadcast_in_dim' op requires the same element type for all operands and results
    return wrapped_exec(params)
^
C:\Users\Edward\Documents\pennylane\pennylane\interfaces\jax_jit.py:253:1: note: see current operation: %1 = "mhlo.broadcast_in_dim"(%0) {broadcast_dimensions = dense<> : tensor<0xi64>} : (tensor<f32>) -> tensor<2x2xf64>
```

Enabling double-precision using `jax.config` gets rid of this error, but this should not be a permanent solution.

**Comment by antalszava** [comment]
> Nice catch @antalszava! Is this a new bug compared to v0.26?

Apologies for the delay! Yes, I tested this locally and it works with v0.26.0. There, I could only do the forward pass because we didn't yet support `jax.jacobian` with jitting (`jax.pure_callback` was not yet used). This issue might actually be related to the change to `jax.pure_callback` (but not sure at this point).

**Comment by albi3ro** [comment]
Still being a problem.

**Comment by albi3ro** [comment]
Solved by #4990
